name: univstore
services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    env_file: .env
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - univstore_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "81:81"
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./api:/app
    networks:
      - univstore_network

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=development
      - PORT=80
      - WATCHPACK_POLLING=true
    env_file: .env
    volumes:
      - ./webapp:/app
      - /app/node_modules
      - /app/.next
    networks:
      - univstore_network

volumes:
  mongodb_data_dev:


networks:
  univstore_network:
    driver: bridge
